# Katzenpost server configuration file.

#
# The Server section contains mandatory information common to all nodes.
#

[Server]

  # Identifier is the human readable identifier for the node (eg: FQDN).
  Identifier = "example5.com"

  # Addresses are the IP address/port combinations that the server will bind
  # to for incoming connections.
  Addresses = [ "127.0.0.1:29485"]

  # DataDir is the absolute path to the server's state files.
  DataDir = "/home/user/.katzenpost/katzenpost5"

  # IsProvider specifies if the server is a provider (vs a mix).
  IsProvider = true

#
# The PKI section contains the directory authority configuration.
#

[PKI]

  # Nonvoting is a simple non-voting PKI for test deployments.
  [PKI.Nonvoting]

    # Address is the IP address/port combination of the directory authority.
    Address = "127.0.0.1:2320"

    # PublicKey is the directory authority's public key in Base64 or Base16 format.
    # PublicKey = "kAiVchOBwHVtKJVFJLsdCQ9UyN2SlfhLHYqT8ePBetg="
    # PublicKey = "900895721381C0756D28954524BB1D090F54C8DD9295F84B1D8A93F1E3C17AD8"
    PublicKey = "A7F65D6EC0C0666B4A58A2FE256E04A1F5B2D5F9459459597C130D37784AA9D3"
#
# The Logging section controls the logging.
#

[Logging]

  # Disable disables logging entirely.
  Disable = false

  # File specifies the log file, if omitted stdout will be used.
  # File = "/var/log/katzenpost.log"

  # Level specifies the log level out of `ERROR`, `WARNING`, `NOTICE`,
  # `INFO` and `DEBUG`.
  #
  # Warning: The `DEBUG` log level is unsafe for production use.
  Level = "DEBUG"

#
# The Provider secton specifies the Provider configuration.
#

[Provider]

  # UserDB is the path to the user database.  If left empty it will use
  # `users.db` under the DataDir.
  # UserDB = ""

  # SpoolDB is the path to the user message spool.  If left empty, it will
  # use `spool.db` under the DataDir.
  # SpoolDB = ""

#
# The Management section specifies the management interface configuration.
#

[Management]

  # Enable enables the management interface.
  Enable = true

  # Path specifies the path to the management interface socket.  If left
  # empty it will use `management_sock` under the DataDir.
  # Path = ""
